README updated (ResolveLocalFileSystem and FileReader)
besport/ocaml-cordova-plugin-file pull request #2
Opened 2021-08-05 14:52 UTC by Thibaut-Gudin

2021-08-23 15:09 UTC, jrochel requested changes

2021-08-23 15:09 UTC, jrochel commented on README.md
> +This function allow to convert URLs into a `DirectoryEntry`, but in this
allows

2021-08-24 08:12 UTC, jrochel commented on README.md
> +indication of what caused the error. Their is 12 differents *error code*
There are 12 different ...
Est-ce que tu peux faire passer un correcteur d'orthographe ?

2021-08-24 13:27 UTC, Thibaut-Gudin commented on README.md
> +indication of what caused the error. Their is 12 differents *error code*
J'ai essayé mais je ne pense pas que ce que j'utilise a corrigé toutes les fautes de conjugaison.

2021-08-31 00:15 UTC, jrochel commented
Il y a encore plein de fautes orthographiques dans cette PR.

2021-08-31 08:22 UTC, Thibaut-Gudin commented
Le site que vous m'avez recommandé a une limite de caractères traité qui est atteinte assez vite à moins de payer un abonnement, ma seule option reste alors libre office qui ne traite pas les erreurs de conjugaisons, je peux tenter de me relire moi même mais même en français je n'ai jamais été très bon en conjugaison.

2021-08-31 08:30 UTC, merged